# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
    - main
    - master
    - dev
    - develop
    - development
    - release
    - release/*
    - feature/*

pool:
  vmImage: ubuntu-latest
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.17.0'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install

  displayName: 'Npm Install'

- script: |
    ng test --watch=false --browsers=ChromeHeadless --code-coverage

  displayName: 'Unit Test'

- script: |
    ng build --configuration production --base-href "/"

  displayName: 'Build'

